In [2]:
import tensorflow as tf

In [50]:
import pandas as pd
import numpy as np
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import cross_val_score
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import RepeatedStratifiedKFold
from sklearn.ensemble import AdaBoostClassifier
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import GridSearchCV
from sklearn.feature_selection import SelectKBest

from sklearn.model_selection import RandomizedSearchCV

In [4]:
fashion_mnist=tf.keras.datasets.fashion_mnist

In [5]:
(X_train,y_train),(X_test,y_test)=fashion_mnist.load_data()

In [6]:
test=np.array(X_test)

In [8]:
test.shape=(10000,28*28)

In [9]:
test

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=uint8)

In [10]:
train=np.array(X_train)

In [14]:
train.shape=(60000,784)

In [15]:
train

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=uint8)

In [35]:
decision_tree = DecisionTreeClassifier()
decision_tree =decision_tree.fit(train,y_train)

In [36]:
decision_tree.score(test,y_test)

0.7913

In [39]:
knn = KNeighborsClassifier()

knn.fit(train,y_train)

KNeighborsClassifier()

In [44]:
cross_val_score(knn,train,y_train,cv=5)

array([0.85741667, 0.84875   , 0.85358333, 0.85875   , 0.8515    ])

In [45]:
knn.score(test,y_test)

0.8554

In [47]:
model = AdaBoostClassifier()
# evaluate the model
#cv = RepeatedStratifiedKFold(n_splits=10, n_repeats=3, random_state=1)
model.fit(train,y_train)

AdaBoostClassifier()

In [49]:
model.score(test,y_test)


0.5425